flowchart TB
  %% Top level
  SmallArms["
  Which **class** best fits?
  **Handguns** or **Long Guns**<br/>
  <img src='' width='56' height='56'/>
  "]

  SmallArms --> Handguns
  SmallArms --> LongGuns

  %% Level 2
  Handguns["Handguns - Which **group** best fits? <br/><img src='' width='56' height='56'/>"]
  LongGuns["Long Guns - Which **group** best fits?<br/><img src='' width='56' height='56'/>"]



  %% Handguns branch
  SelfLoadingPistols["Self-loading<br/>Pistols<br/><img src='' width='56' height='56'/>"]
  Revolvers["Revolvers<br/><img src='' width='56' height='56'/>"]
  OtherHandguns["Other Handguns<br/><img src='' width='56' height='56'/>"]

  Handguns --> SelfLoadingPistols
  Handguns --> Revolvers
  Handguns --> OtherHandguns

  %% Long guns branch (first row under Long Guns)
  SubMachineGuns["Sub-machine<br/>Guns<br/><img src='' width='56' height='56'/>"]
  ManPortableMachineGuns["Man-portable<br/>Machine Guns<br/><img src='' width='56' height='56'/>"]
  Rifles["Rifles<br/><img src='' width='56' height='56'/>"]
  Shotguns["Shotguns<br/><img src='' width='56' height='56'/>"]
  OtherLongGuns["Other Long<br/>Guns<br/><img src='' width='56' height='56'/>"]

  LongGuns --> SubMachineGuns
  LongGuns --> ManPortableMachineGuns
  LongGuns --> Rifles
  LongGuns --> Shotguns
  LongGuns --> OtherLongGuns

  %% Rifles split
  SelfLoadingRifles["Self-loading<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  ManuallyOperatedRifles["Manually<br/>Operated Rifles<br/><img src='' width='56' height='56'/>"]

  Rifles --> SelfLoadingRifles
  Rifles --> ManuallyOperatedRifles

  %% Shotguns split
  SelfLoadingShotguns["Self-loading<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  ManuallyOperatedShotguns["Manually<br/>Operated Shotguns<br/><img src='' width='56' height='56'/>"]

  Shotguns --> SelfLoadingShotguns
  Shotguns --> ManuallyOperatedShotguns

  %% Self-loading rifles leaves
  AutomaticRifles["Automatic Rifles<br/><img src='' width='56' height='56'/>"]
  SemiAutomaticRifles["Semi-automatic<br/>Rifles<br/><img src='' width='56' height='56'/>"]

  SelfLoadingRifles --> AutomaticRifles
  SelfLoadingRifles --> SemiAutomaticRifles

  %% Manually operated rifles leaves
  BreakActionRifles["Break-action<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  BoltActionRifles["Bolt-action<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  LeverActionRifles["Lever-action<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  PumpActionRifles["Pump-action<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  OtherManuallyOperatedRifles["Other Manually<br/>Operated Rifles<br/><img src='' width='56' height='56'/>"]

  ManuallyOperatedRifles --> BreakActionRifles
  ManuallyOperatedRifles --> BoltActionRifles
  ManuallyOperatedRifles --> LeverActionRifles
  ManuallyOperatedRifles --> PumpActionRifles
  ManuallyOperatedRifles --> OtherManuallyOperatedRifles

  %% Self-loading shotguns leaves
  AutomaticShotguns["Automatic Shotguns<br/><img src='' width='56' height='56'/>"]
  SemiAutomaticShotguns["Semi-automatic<br/>Shotguns<br/><img src='' width='56' height='56'/>"]

  SelfLoadingShotguns --> AutomaticShotguns
  SelfLoadingShotguns --> SemiAutomaticShotguns

  %% Manually operated shotguns leaves
  BreakActionShotguns["Break-action<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  BoltActionShotguns["Bolt-action<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  LeverActionShotguns["Lever-action<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  PumpActionShotguns["Pump-action<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  OtherManuallyOperatedShotguns["Other Manually<br/>Operated Shotguns<br/><img src='' width='56' height='56'/>"]

  ManuallyOperatedShotguns --> BreakActionShotguns
  ManuallyOperatedShotguns --> BoltActionShotguns
  ManuallyOperatedShotguns --> LeverActionShotguns
  ManuallyOperatedShotguns --> PumpActionShotguns
  ManuallyOperatedShotguns --> OtherManuallyOperatedShotguns
