flowchart TB
  %% Top level
  SmallArms["Which Small Arms **group** best fits?<br/><img src='' width='56' height='56'/>"]

  SmallArms --> |Handguns| Handguns
  SmallArms --> |Long Guns| LongGuns

  Handguns["Which **barrel type** best fits?<br/><img src='' width='56' height='56'/>"]

  %% Bore-type breaks
  Handguns --> |Rifled| Handguns_Rifled
  Handguns --> |Smooth Bore| SmoothBore_OtherHandguns

  %% Handguns details
  Handguns_Rifled["Which type of rifiled handgun best matches?<br/><img src='' width='56' height='56'/>"]
  Handguns_Rifled --> |Self Loading Pistols| Rifled_SelfLoadingPistols
  Handguns_Rifled --> |Revolvers| Rifled_Revolvers

  SmoothBore_OtherHandguns["Other handguns<br/><img src='' width='56' height='56'/>"]

  %% Long guns details
  LongGuns["Which **barrel type** best fits?<br/><img src='' width='56' height='56'/>"]

  LongGuns --> |Rifled| LongGuns_Rifled
  LongGuns --> |Smooth Bore| LongGuns_SmoothBore

  Rifled_SelfLoadingPistols["Self-loading<br/>Pistols<br/><img src='' width='56' height='56'/>"]
  Rifled_Revolvers["Revolvers<br/><img src='' width='56' height='56'/>"]

  LongGuns_Rifled["Which type of **rifiled long gun** best matches?<br/><img src='' width='56' height='56'/>"]
  Rifled_SubMachineGuns["Sub-machine<br/>guns<br/><img src='' width='56' height='56'/>"]
  Rifled_ManPortableMachineGuns["Man-portable<br/>machine guns<br/><img src='' width='56' height='56'/>"]
  
  LongGuns_SmoothBore["Smooth-bore<br/><img src='' width='56' height='56'/>"]

  LongGuns_Rifled --> |Sub-machine Guns| Rifled_SubMachineGuns
  LongGuns_Rifled --> |Man-portable Machine Guns| Rifled_ManPortableMachineGuns
  LongGuns_Rifled --> |Other| Rifles

  LongGuns_SmoothBore --> |Shotguns| Shotguns
  LongGuns_SmoothBore --> |OtherSmoothBoreLongGuns| OtherSmoothBoreLongGuns

  Rifles["Rifles: Which **sub-type** of **rifled long guns** matches best?<br/><img src='' width='56' height='56'/>"]
  
  Rifles --> |Self-Loading| SelfLoadingRifles
  Rifles --> |Manually-Loaded| ManuallyOperatedRifles

  Shotguns["How is amunition loaded into the shotgun?<br/><img src='' width='56' height='56'/>"]
  OtherSmoothBoreLongGuns["Other smooth-bore<br/>long guns<br/><img src='' width='56' height='56'/>"]

  %% Rifles split
  SelfLoadingRifles["Which operation method of **self-loading rifled long gun** best fits?<br/><img src='' width='56' height='56'/>"]
  ManuallyOperatedRifles["Which operation method **manually-loading rifled long gun** best fits?<br/><img src='' width='56' height='56'/>"]

  %% Self-loading rifles leaves
  AutomaticRifles["Automatic Rifles<br/><img src='' width='56' height='56'/>"]
  SemiAutomaticRifles["Semi-automatic<br/>Rifles<br/><img src='' width='56' height='56'/>"]

  SelfLoadingRifles --> |Automatic Rifles| AutomaticRifles
  SelfLoadingRifles --> |SemiAutomatic Rifles| SemiAutomaticRifles

  %% Manually operated rifles leaves
  BreakActionRifles["Break-action<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  BoltActionRifles["Bolt-action<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  LeverActionRifles["Lever-action<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  PumpActionRifles["Pump-action<br/>Rifles<br/><img src='' width='56' height='56'/>"]
  OtherManuallyOperatedRifles["Other Manually<br/>Operated Rifles<br/><img src='' width='56' height='56'/>"]

  ManuallyOperatedRifles --> |BreakActionRifles| BreakActionRifles
  ManuallyOperatedRifles --> |BoltActionRifles|BoltActionRifles
  ManuallyOperatedRifles --> |LeverActionRifles| LeverActionRifles
  ManuallyOperatedRifles --> |PumpActionRifles| PumpActionRifles
  ManuallyOperatedRifles --> |OtherManuallyOperatedRifles| OtherManuallyOperatedRifles

  %% Shotguns split (matches reference structure)
  SelfLoadingShotguns["Self-loading Shotguns<br/><img src='' width='56' height='56'/>"]
  ManuallyOperatedShotguns["Manually Operated Shotguns<br/><img src='' width='56' height='56'/>"]

  Shotguns --> |Self-Loading| SelfLoadingShotguns
  Shotguns --> |Manually| ManuallyOperatedShotguns

  %% Self-loading shotguns leaves
  AutomaticShotguns["Automatic Shotguns<br/><img src='' width='56' height='56'/>"]
  SemiAutomaticShotguns["Semi-automatic<br/>Shotguns<br/><img src='' width='56' height='56'/>"]

  SelfLoadingShotguns --> |AutomaticShotguns| AutomaticShotguns
  SelfLoadingShotguns --> |SemiAutomaticShotguns| SemiAutomaticShotguns

  %% Manually operated shotguns leaves
  BreakActionShotguns["Break-action<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  BoltActionShotguns["Bolt-action<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  LeverActionShotguns["Lever-action<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  PumpActionShotguns["Pump-action<br/>Shotguns<br/><img src='' width='56' height='56'/>"]
  OtherManuallyOperatedShotguns["Other Manually<br/>Operated Shotguns<br/><img src='' width='56' height='56'/>"]

  ManuallyOperatedShotguns --> |BreakActionShotguns| BreakActionShotguns
  ManuallyOperatedShotguns --> |BoltActionShotguns| BoltActionShotguns
  ManuallyOperatedShotguns --> |LeverActionShotguns| LeverActionShotguns
  ManuallyOperatedShotguns --> |PumpActionShotguns| PumpActionShotguns
  ManuallyOperatedShotguns --> |OtherManuallyOperatedShotguns| OtherManuallyOperatedShotguns

