flowchart TB
  Small_Arms["<h1>Which Small Arms group best fits?</h1><p></p><img src="" />"]
  Handgun["<h1>Which barrel type best fits what you see?</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.4_Rifled_and_smooth-bore_barrels.png?raw=true" />"]
  Rifled["<h1>Which type of rifled handgun best matches?</h1><p></p><img src="" />"]
  Revolver["<h1>Revolver</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/ARES_arms_munitions_classification_system/visuals/Figure2.12_Revolvers.png?raw=true" />"]
  Self_Loading_Pistol["<h1>Self-Loading Pistol</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/ARES_arms_munitions_classification_system/visuals/Figure2.13_SelfLoading_Pistols.png?raw=true" />"]
  Smooth_Bore["<h1>Which type of rifled handgun best matches?</h1><p></p><img src="" />"]
  Other_Handguns["<h1>Other Handguns</h1><p></p><img src="" />"]
  Long_Gun["<h1>Which barrel type best fits?</h1><p></p><img src="" />"]
  Automatic_Rifle["<h1>Automatic Rifle</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.1_Typical_features_of_a_modern_military_rifle.png?raw=true" />"]
  Bolt_Action_Rifle["<h1>Bolt-Action Rifle</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.1_Typical_features_of_a_modern_military_rifle.png?raw=true" />"]
  Break_Action_Rifle["<h1>Break-Action Rifle</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.1_Typical_features_of_a_modern_military_rifle.png?raw=true" />"]
  Lever_Action_Rifle["<h1>Lever-Action Rifle</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.1_Typical_features_of_a_modern_military_rifle.png?raw=true" />"]
  Man_Portable_Machine_Gun["<h1>Man-Portable Machine Gun</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.1_Typical_features_of_a_modern_military_rifle.png?raw=true" />"]
  Other_Manually_Operated_Rifles["<h1>Other Manually Operated Rifles</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.1_Typical_features_of_a_modern_military_rifle.png?raw=true" />"]
  Pump_Action_Rifle["<h1>Pump-Action Rifle</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.8_Typical_features_of_a_pump-action_shotgun.png?raw=true" />"]
  Semi_Automatic_Rifle["<h1>Semi-Automatic Rifle</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.1_Typical_features_of_a_modern_military_rifle.png?raw=true" />"]
  Sub_Machine_Gun["<h1>Sub-Machine Gun</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.1_Typical_features_of_a_modern_military_rifle.png?raw=true" />"]
  Automatic_Shotgun["<h1>Automatic Shotgun</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.4_Rifled_and_smooth-bore_barrels.png?raw=true" />"]
  Bolt_Action_Shotgun["<h1>Bolt-Action Shotgun</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.4_Rifled_and_smooth-bore_barrels.png?raw=true" />"]
  Break_Action_Shotgun["<h1>Break-Action Shotgun</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.7_Typical_features_of_a_break-action_shotgun.png?raw=true" />"]
  Lever_Action_Shotgun["<h1>Lever-Action Shotgun</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.4_Rifled_and_smooth-bore_barrels.png?raw=true" />"]
  Other_Manually_Operated_Shotguns["<h1>Other Manually Operated Shotguns</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.4_Rifled_and_smooth-bore_barrels.png?raw=true" />"]
  Other_Smooth_Bore_Long_Guns["<h1>Other Smooth Bore Long Guns</h1><p></p><img src="" />"]
  Pump_Action_Shotgun["<h1>Pump-Action Shotgun</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/small_arms_survey/visuals/Figure_3.8_Typical_features_of_a_pump-action_shotgun.png?raw=true" />"]
  Semi_Automatic_Shotgun["<h1>Semi-Automatic Shotgun</h1><p></p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/ARES_arms_munitions_classification_system/visuals/Figure2.20_Compare_Barrel_Types_Shotgun.png?raw=true" />"]

  Small_Arms --> |"<h1>Handgun</h1><p>a firearm which is grasped by placing both the control hand and support hand around the pistol grip, and which may be readily fired with one hand (ARES p37)</p><img src="https://github.com/paigemoody/weapons_classification_resources.github.io/blob/gh-pages/sources/ARES_arms_munitions_classification_system/visuals/Figure2.8_2.9_2.10_Handguns.png?raw=true" />"| Handgun
  Handgun --> |"<h1>Rifled</h1><p></p><img src="" />"| Rifled
  Rifled --> |"<h1>Revolver</h1><p></p><img src="" />"| Revolver
  Rifled --> |"<h1>Self-Loading Pistol</h1><p></p><img src="" />"| Self_Loading_Pistol
  Handgun --> |"<h1>Smooth Bore</h1><p></p><img src="" />"| Smooth_Bore
  Smooth_Bore --> |"<h1>Other Handguns</h1><p></p><img src="" />"| Other_Handguns
  Small_Arms --> |"<h1>Long Gun</h1><p>A firearm which is grasped by placing the control hand and support hand in different locations, and which is typically fitted with a buttstock intended to be braced against the user's shoulder when fired.</p><img src="" />"| Long_Gun
  Rifled --> |"<h1>Automatic Rifle</h1><p></p><img src="" />"| Automatic_Rifle
  Rifled --> |"<h1>Bolt-Action Rifle</h1><p></p><img src="" />"| Bolt_Action_Rifle
  Rifled --> |"<h1>Break-Action Rifle</h1><p></p><img src="" />"| Break_Action_Rifle
  Rifled --> |"<h1>Lever-Action Rifle</h1><p></p><img src="" />"| Lever_Action_Rifle
  Rifled --> |"<h1>Man-Portable Machine Gun</h1><p></p><img src="" />"| Man_Portable_Machine_Gun
  Rifled --> |"<h1>Other Manually Operated Rifles</h1><p></p><img src="" />"| Other_Manually_Operated_Rifles
  Rifled --> |"<h1>Pump-Action Rifle</h1><p></p><img src="" />"| Pump_Action_Rifle
  Rifled --> |"<h1>Semi-Automatic Rifle</h1><p></p><img src="" />"| Semi_Automatic_Rifle
  Rifled --> |"<h1>Sub-Machine Gun</h1><p></p><img src="" />"| Sub_Machine_Gun
  Smooth_Bore --> |"<h1>Automatic Shotgun</h1><p></p><img src="" />"| Automatic_Shotgun
  Smooth_Bore --> |"<h1>Bolt-Action Shotgun</h1><p></p><img src="" />"| Bolt_Action_Shotgun
  Smooth_Bore --> |"<h1>Break-Action Shotgun</h1><p></p><img src="" />"| Break_Action_Shotgun
  Smooth_Bore --> |"<h1>Lever-Action Shotgun</h1><p></p><img src="" />"| Lever_Action_Shotgun
  Smooth_Bore --> |"<h1>Other Manually Operated Shotguns</h1><p></p><img src="" />"| Other_Manually_Operated_Shotguns
  Smooth_Bore --> |"<h1>Other Smooth Bore Long Guns</h1><p></p><img src="" />"| Other_Smooth_Bore_Long_Guns
  Smooth_Bore --> |"<h1>Pump-Action Shotgun</h1><p></p><img src="" />"| Pump_Action_Shotgun
  Smooth_Bore --> |"<h1>Semi-Automatic Shotgun</h1><p></p><img src="" />"| Semi_Automatic_Shotgun